/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/model.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh geometry={nodes.mesh0.geometry} material={materials.Material_0} />
      <mesh geometry={nodes.mesh1.geometry} material={materials.Material_1} />
      <mesh geometry={nodes.mesh2.geometry} material={materials.Material_2} />
      <mesh geometry={nodes.mesh3.geometry} material={materials.Material_3} />
      <mesh geometry={nodes.mesh4.geometry} material={materials.Material_4} />
      <mesh geometry={nodes.mesh5.geometry} material={materials.Material_5} />
      <mesh geometry={nodes.mesh6.geometry} material={materials.Material_6} />
      <mesh geometry={nodes.mesh7.geometry} material={materials.Material_7} />
      <mesh geometry={nodes.mesh8.geometry} material={materials.Material_8} />
      <mesh geometry={nodes.mesh9.geometry} material={materials.Material_9} />
      <mesh geometry={nodes.mesh10.geometry} material={materials.Material_10} />
      <mesh geometry={nodes.mesh11.geometry} material={materials.Material_11} />
      <mesh geometry={nodes.mesh12.geometry} material={materials.Material_12} />
      <mesh geometry={nodes.mesh13.geometry} material={materials.Material_13} />
      <mesh geometry={nodes.mesh14.geometry} material={materials.Material_14} />
      <mesh geometry={nodes.mesh15.geometry} material={materials.Material_15} />
      <mesh geometry={nodes.mesh16.geometry} material={materials.Material_16} />
      <mesh geometry={nodes.mesh17.geometry} material={materials.Material_17} />
      <mesh geometry={nodes.mesh18.geometry} material={materials.Material_18} />
      <mesh geometry={nodes.mesh19.geometry} material={materials.Material_19} />
      <mesh geometry={nodes.mesh20.geometry} material={materials.Material_20} />
      <mesh geometry={nodes.mesh21.geometry} material={materials.Material_21} />
      <mesh geometry={nodes.mesh22.geometry} material={materials.Material_22} />
      <mesh geometry={nodes.mesh23.geometry} material={materials.Material_23} />
      <mesh geometry={nodes.mesh24.geometry} material={materials.Material_24} />
      <mesh geometry={nodes.mesh25.geometry} material={materials.Material_25} />
      <mesh geometry={nodes.mesh26.geometry} material={materials.Material_26} />
      <mesh geometry={nodes.mesh27.geometry} material={materials.Material_27} />
    </group>
  )
}

useGLTF.preload('/model.gltf')
